version: "3.6"
services:
  explainai-postgres:
    container_name: explainai-postgres
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  explainai-hasura:
    container_name: explainai-hasura
    image: hasura/graphql-engine:v2.19.0-ce.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "explainai-postgres"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
      DATABASE_URL: postgres://postgres:postgrespassword@explainai-postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@explainai-postgres:5432/postgres
      API_ENDPOINT: http://host.docker.internal:3000
  # explainai-nextjs:
  #   build:
  #     context: ./nextjs
  #     target: runner
  #   depends_on:
  #     - "explainai-hasura"
  #   volumes:
  #     - ./nextjs:/app
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     REVALIDATE_SECRET: secret
volumes:
  db_data:
