import Header from "../components/Header";
import "./styles.css";
import dynamic from "next/dynamic";

import { Analytics } from "@vercel/analytics/react";
import Splash from "../components/Splash";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Inner({ children }: any) {
  return <main>{children}</main>;
}

export default function App({ Component, pageProps }: any) {
  return (
    <>
      <Header {...pageProps} />
      {pageProps.page === "groups" && <Splash />}
      <Inner>
        <Component {...pageProps} />
      </Inner>
      <Analytics />
    </>
  );
}
